return {
  { "akinsho/bufferline.nvim", enabled = false },
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  { "rcarriga/nvim-notify", enabled = false },
  { "folke/flash.nvim", enabled = false },
  -- { "nvimtools/none-ls.nvim", enabled = false },
  { "stevearc/dressing.nvim", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "RRethy/vim-illuminate", enabled = false },
  { "folke/neoconf.nvim", enabled = false },
  -- { "nvim-telescope/telescope.nvim", enabled = false },
  { "JoosepAlviste/nvim-ts-context-commentstring", enabled = false },
  { "echasnovski/mini.comment", enabled = false },
  { "echasnovski/mini.bufremove", enabled = false },
  { "echasnovski/mini.surround", enabled = false },
  -- { "echasnovski/mini.pairs", enabled = false },
  { "echasnovski/mini.ai", enabled = false },
}
